name: syncreve
description: Cross-platform file sync client for Cloudreve

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  riverpod: ^2.3.2
  dio: ^5.1.0
  fluttertoast: ^8.1.3
  flutter_easyloading: ^3.0.5
  pull_to_refresh_flutter3: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.7.0
  crypto: ^3.0.2
  flutter_inappwebview: ^6.0.0-beta.22
  path_provider: ^2.0.14
  font_awesome_flutter: ^10.4.0
  flutter_staggered_grid_view: ^0.6.2
  extended_image: ^8.0.2
  protobuf: ^3.0.0
  grpc: ^3.1.0
  open_file_plus: ^3.4.0
  filesize: ^2.0.1
  flutter_svg: ^2.0.4
  mobile_scanner: ^3.2.0
  cupertino_icons: ^1.0.2
  fixnum: ^1.1.0
  http2: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true